
                  "PREFIX er:  <http://od.cs.pub.ro/privatesector/election_result/> "
                + "PREFIX com: <http://od.cs.pub.ro/privatesector/company/> "
                + "PREFIX ps:  <http://od.cs.pub.ro/privatesector/> "
                + "SELECT * WHERE { "
                + "{"
                + " SELECT ?result ?party ?votes ?name"
                + " WHERE {"
                + "     ?result com:locatedIn <http://od.cs.pub.ro/privatesector/location/ALBA_Zlatna> . "
                + "     ?result er:forParty ?party . "
                + "     ?party ps:name ?name ."
                + "     ?result er:totalVotes ?votes ."
                + " } ORDER BY DESC(xsd:integer(?votes)) LIMIT 1"
                + "} UNION {"
                + " SELECT (COUNT(*) AS ?count)"
                + " WHERE {"
                + "      ?company ps:location ?location"
                + " } GROUP BY ?location"
                + "}"
                + "}";